pipeline {
    agent any
    stages {
        stage("build"){
            steps {
                sh 'docker image prune -a --force'
                sh 'docker build -t wlsgh97/coalla-node-server ./frontend/node'
                sh 'docker build -t wlsgh97/coalla-frontend ./frontend --build-arg OAUTH_REDIRECT_URL=${OAUTH_REDIRECT_URL} --build-arg API_URL=${API_URL}'
                sh 'echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin'
                echo 'Build image...'
                sh "docker push wlsgh97/coalla-frontend"
                sh "docker push wlsgh97/coalla-node-server"
                script{
                    try {
                        sh 'docker stop node-server'
                        sh 'docker rm node-server'
                        // sh 'docker rmi wlsgh97/coalla-node-server'
                    } catch (e) {
                        sh 'echo "fail to stop and remove node-server container"'
                    }
                    try {
                        sh 'docker stop frontend'
                        sh 'docker rm frontend'
                        // sh 'docker rmi wlsgh97/coalla-frontend'
                    } catch (e) {
                        sh 'echo "fail to stop and remove container"'
                    }
                }
                sh "docker run -d -p 3000:3000 --name frontend wlsgh97/coalla-frontend"
                sh "docker run -d -p 8000:8000 --name node-server wlsgh97/coalla-node-server"
            }
        }    
    }    
}
